#!/bin/sh

# Export runtime environment variables
export API_KEY=${API_KEY}
export COGNITO_DOMAIN=${COGNITO_DOMAIN}
export USER_POOL_ID=${USER_POOL_ID}
export AWS_REGION=${AWS_REGION}
export APP_CLIENT_ID=${APP_CLIENT_ID}
export APP_CLIENT_SECRET=${APP_CLIENT_SECRET}
export REDIRECT_SIGNIN=${REDIRECT_SIGNIN}
export REDIRECT_SIGNOUT=${REDIRECT_SIGNOUT}

exec "$@"
