#!/bin/sh

# Export runtime environment variables
export NEXT_PUBLIC_API_KEY=${API_KEY}
export NEXT_PUBLIC_COGNITO_DOMAIN=${COGNITO_DOMAIN}
export NEXT_PUBLIC_USER_POOL_ID=${USER_POOL_ID}
export NEXT_PUBLIC_AWS_REGION=${AWS_REGION}
export NEXT_PUBLIC_APP_CLIENT_ID=${APP_CLIENT_ID}
export NEXT_PUBLIC_APP_CLIENT_SECRET=${APP_CLIENT_SECRET}
export NEXT_PUBLIC_REDIRECT_SIGNIN=${REDIRECT_SIGNIN}
export NEXT_PUBLIC_REDIRECT_SIGNOUT=${REDIRECT_SIGNOUT}

exec "$@"
